### PR TITLE
LPS-131148, LPS-131149 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-131148
https://issues.liferay.com/browse/LPS-131149

This is only for master.

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:staging

**Comment by Tim-Cao** [comment]
The WorkflowMetrics#ViewReports is a common failure unrelated to the changes in PR.

**Comment by Tim-Cao** [comment]
RemoteStaging#StagingRemoteLiveWebContent and Staging#PublishVocabularyDeletionViaRemoteStagingOnGlobalSite are remote staging cases unrelated the changes in this PR too.

**Comment by Tim-Cao** [comment]
See https://github.com/moltam89/liferay-portal/pull/613

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
