### PR TITLE
LPS-118794 Use staging page for preview when group is staged locally since there can be no Live pages published yet

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/1818

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
