### PR TITLE
LPS-130946 DateConverter in jodd 6 uses Java 8 LocalDateTime.parse to parse the date string, which sticks to a strict pattern. Provide a converter to use DateTimeFormatter with optional parts to support multiple formats in string parsing.

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@Tim-Cao Please verify this fix & review the ci results, thanks!

**Comment by Tim-Cao** [comment]
Hi @dantewang, the failure acceptance case is unrelated to your changes. I will verify your fix on my local tomorrow morning.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by Tim-Cao** [comment]
Hi @dantewang, Looks good enough after I validated on local.

**Comment by dantewang** [comment]
@Tim-Cao Thanks! I'll wait for ci-test result.

**Pull request closed without merging**
