### PR TITLE
bchan

### PR DESCRIPTION
**Pull request by kyle-miho**

### CODE REVIEW

**Comment by kyle-miho** [comment]
Currently rebased up to Bchans branch, but test to see if this fixed the original fix, I think you meant * instead of +, since we shouldnt be required to parse extra characters afterwards.

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
ci:help

**Comment by Tim-Cao** [comment]
ci:test:headless-functional

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/140329

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
