### PR TITLE
POSHI-228

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/POSHI-228

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:acceptance-functional

**Comment by Tim-Cao** [comment]
Hi @kenjiheigel, no failure is related to this PR.

**Comment by kenjiheigel** [comment]
ci:reevaluate:1317401_1545

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:forward

**Pull request closed without merging**
