### PR TITLE
LPS-123141 Inject missing theme display

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
Thanks @pavel-savinov @Tim-Cao Can you remove the first three commits, I just added them to see if the failures are caused by them.

**Comment by ling-alan-huang** [comment]
And rename `layout_page_template` to `layout_page_template_admin`.

https://github.com/Tim-Cao/liferay-portal/pull/528/commits/3a1d376402adf500216e87c7c17329002daa1be7#diff-4d6a92a8690b3a16ae9c311754700c394df4eec076ebffd920423ac7a94bf015R133

https://github.com/Tim-Cao/liferay-portal/pull/528/commits/3a1d376402adf500216e87c7c17329002daa1be7#diff-cbf0e6ffa4e04e71b200a8c9d10aa179cc08486c802c262776dd15b2b4ad77d5R144

Thanks.

**Comment by Tim-Cao** [comment]
See https://github.com/ling-alan-huang/liferay-portal/pull/339

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
