### PR TITLE
LPS-131149, LPS-131433 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-131433
https://issues.liferay.com/browse/LPS-131149

This is only for master.

@kyle-miho

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
CPCommerceProducts#ProductPublishing is unrelated to changes in PR.

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
@jkappler @Tim-Cao fyi i submitted the pr for the PortletServiceImpl changes to shuyang here: https://github.com/shuyangzhou/liferay-portal/pull/9997

**Comment by Tim-Cao** [comment]
Thanks @kyle-miho

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/4446

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
