### PR TITLE
LPS-116983 Adapt poshi tests

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @jkappler The page redirects to blank URL when click Page Tree. Could you have a look at?
Video

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
See https://github.com/jkappler/liferay-portal/pull/857

**Pull request closed without merging**
