### PR TITLE
LRQA-60243 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRQA-60243

This is only for master.

@manoelcyreno
@kenjiheigel

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @kenjiheigel, I think we should revert 88d517b79fa538e8138cf421f3ef7b2f9dad41ad not 336422fa14e6ad418033d7f50ac6d7ffb58b07ba

**Comment by Tim-Cao** [comment]
Hi @kenjiheigel, Could you help me? If not execute test.poshi.runner.local.release=true, the above issue will occur. How to send this PR?

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
Reason for failure earlier was because the new poshi gradle plugin hadn't been published. BChan just published it earlier this morning, hopefully it should pass now.

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
@kenjiheigel  Thanks

**Pull request closed without merging**
