### PR TITLE
LPS-126220

### PR DESCRIPTION
**Pull request by nikki-pru**
https://issues.liferay.com/browse/LPS-126220

### CODE REVIEW

**Comment by nikki-pru** [comment]
SF, Stable, Relevant passed in https://github.com/nikki-pru/liferay-portal/pull/63

**Comment by nikki-pru** [comment]
cc @david-gutierrez-mesa

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
Review done in david-gutierrez-mesa#126

**Comment by david-gutierrez-mesa** [comment]
ci:close

**Pull request closed without merging**
