### PR TITLE
LRQA-73815 | master

### PR DESCRIPTION
**Pull request by yanan**
https://issues.liferay.com/browse/LRQA-73815
cc @Tim-Cao

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
@yanan Try to add task block

**Comment by yanan** [comment]
Will send another pull request, closing this.

**Comment by Tim-Cao** [comment]
See https://github.com/Tim-Cao/liferay-portal/pull/689

**Pull request closed without merging**
