### PR TITLE
master-qa-102531-ci

### PR DESCRIPTION
**Pull request by Tim-Cao**
ci:test

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test

**Comment by manoelcyreno** [comment]
ci:test:sf

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
@Tim-Cao , about your modification on test.properties, and the "property portal.acceptance = "true"" ... in the commit of the "CI test only" remember to come back to the original.

**Pull request closed without merging**
