### PR TITLE
LPS-126228 | master

### PR DESCRIPTION
**Pull request by nikki-pru**
Forwarding from https://github.com/nikki-pru/liferay-portal/pull/59.

https://issues.liferay.com/browse/LPS-126228

cc/ @joepak

### CODE REVIEW

**Comment by nikki-pru** [comment]
Passed stable and sf in https://github.com/nikki-pru/liferay-portal/pull/59.

Relevant failures in previous PR were not related to the changes committed.

**Comment by david-gutierrez-mesa** [comment]
ci:forward

**Comment by david-gutierrez-mesa** [comment]
LGTM

**Comment by david-gutierrez-mesa** [comment]
ci:stop

**Comment by david-gutierrez-mesa** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/98408

**Comment by david-gutierrez-mesa** [comment]
ci:close

**Pull request closed without merging**
