### PR TITLE
LRQA-73815 | master

### PR DESCRIPTION
**Pull request by lilylcl**
https://issues.liferay.com/browse/LRQA-73815
@Tim-Cao

### CODE REVIEW

**Comment by lilylcl** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
Good job @lilylcl

**Comment by Tim-Cao** [comment]
See https://github.com/Sharryxue/liferay-portal/pull/394

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
