### PR TITLE
POSHI-12 Add new methods for handling JavaScript popups

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/POSHI-12

@Tim-Cao, @david-gutierrez-mesa, I tested out the methods using the files that I commited in the 'DO NOT MERGE' commits. It's the same implementation that Tim sent me originally, but reworked so it can eventually replace all those confirmation methods. I'm pretty sure it will work fine, so I sent it to Peter for review: https://github.com/pyoo47/liferay-portal/pull/1651. Let me know if there are any questions or issues though. 

Also, if you guys need to make a function file. Don't call it Alert.function. There is a bug. It will break Poshi Script parsing since there happens to be a file named Alert.macro also lol.

### CODE REVIEW

**Comment by Tim-Cao** [comment]
Hi @kenjiheigel, the acceptAlert and dismissAlert work on my local. However, assertAlertText will throw NPE
`     [exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.WebContentWithCustomStructures#ResetStructureDefaultValues] STANDARD_ERROR
     [exec]     java.lang.NullPointerException
     [exec]             at com.liferay.poshi.runner.selenium.BaseWebDriverImpl.assertAlertText(BaseWebDriverImpl.java:246)
     [exec]             at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]             at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]             at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]             at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]             at com.liferay.poshi.runner.PoshiRunnerExecutor$1.call(PoshiRunnerExecutor.java:1190)
     [exec]             at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [exec]             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     [exec]             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     [exec]             at java.lang.Thread.run(Thread.java:748)
     [exec]
     [exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.WebContentWithCustomStructures#ResetStructureDefaultValues] STANDARD_OUT
     [exec]     Test retry attempts exceeded in Poshi Runner JVM
     [exec]
     [exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.WebContentWithCustomStructures#ResetStructureDefaultValues] FAILED
     [exec]     java.lang.NullPointerException at BaseWebDriverImpl.java:246`

**Comment by kenjiheigel** [comment]
@Tim-Cao , it seemed to work for me locally without issue. Might be an issue with the caching. BChan published the new version, so right now simplest to just use that. I'll update this pull to use the new version.

**Comment by kenjiheigel** [comment]
@Tim-Cao , all the methods worked for me when I ran it locally. Try this, and let me know if you still have issues.

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @kenjiheigel, the NPE is still thrown   
 ```
[exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.WebContentWithCustomStructures#ResetStructureDefaultValues] STANDARD_ERROR
     [exec]     java.lang.NullPointerException
     [exec]             at com.liferay.poshi.runner.selenium.BaseWebDriverImpl.assertAlertText(BaseWebDriverImpl.java:246)
     [exec]             at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]             at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]             at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]             at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]             at com.liferay.poshi.runner.PoshiRunnerExecutor$1.call(PoshiRunnerExecutor.java:1190)
     [exec]             at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [exec]             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     [exec]             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     [exec]             at java.lang.Thread.run(Thread.java:748)
     [exec]
     [exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.WebContentWithCustomStructures#ResetStructureDefaultValues] STANDARD_OUT
     [exec]     Test retry attempts exceeded in Poshi Runner JVM
     [exec]
     [exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.WebContentWithCustomStructures#ResetStructureDefaultVa

```

**Pull request closed without merging**
